# Generated by Django 2.2 on 2020-05-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=114)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
